[build-system]
requires = ["setuptools>=61.0.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "foundation_llm"
version = "0.1.0"
description = "A foundational LLM codebase"
readme = "README.md"
requires-python = ">=3.8"
dependencies = [
    "matplotlib",
    "pyarrow",
    "pyspark",
    "pyyaml",
    "tensorboard",
    "tiktoken",
    "torch",
    "transformers",
]

[project.optional-dependencies]
dev = [
    "pytest",
]
